import Head from "next/head";
import styles from "../styles/Home.module.css";

const DUMMY_DATA = [
  { id: "m1", name: "person1" },
  { id: "m2", name: "person2" },
  { id: "m3", name: "person3" },
  { id: "m4", name: "person4" },
  { id: "m5", name: "person5" },
];

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next JS Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
          {props.data.map((item) => (
            <li key={item.id}>{item.name}</li>
          ))}
        </ul>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  return {
    props: {
      data: DUMMY_DATA,
    },
  };
}
